[package]
name = "rustling-ontology-values"
version = "0.17.5"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]

[dependencies]
failure = "0.1"
regex = "1.0"
rustling = { git="https://github.com/maenzhier/rustling" }
rustling-ontology-moment = { path="../moment"}
