[package]
name = "rustling-ontology-de"
version = "0.17.5"
authors = [""]

[dependencies]
rustling = { git="https://github.com/maenzhier/rustling", tag="0.9.0" }
rustling-ontology-moment = { path="../../moment"}
rustling-ontology-values = { path="../../values"}
