[package]
name = "rustling-ontology-en"
version = "0.17.5"
authors = ["maenzhier"]

[dependencies]
rustling = { git="https://github.com/maenzhier/rustling"}
rustling-ontology-moment = { path="../../moment"}
rustling-ontology-values = { path="../../values"}